### ISSUE TITLE
「平」部件寫法不一

### ISSUE THREAD

**Issue by lapomme** [justfont/open-huninn-font#12]
![image](https://user-images.githubusercontent.com/27000939/76815813-0652b500-67d5-11ea-9006-f8c87947c54a.png)

**Comment by i-font** [comment]
這字體使用了基礎的傳承字形為部分漢字的基礎，在傳統印刷字形中，長期以來都作「⿻干ハ」形而非「⿻干丷」形。因此建議統一改作「⿻干ハ」形，即是依從上圖中紅字的寫法。

**Comment by rutopio** [comment]
謝謝您告訴我們，我們會在未來的新版本中修正。

It will be fixed in our upcoming version soon, thank you.

**Comment by rutopio** [comment]
`平` 偏旁的字符已於 `2.0` 版本中統一部件。

<img width="1150" alt="image" src="https://github.com/user-attachments/assets/5b060e99-12e7-4bcf-a16c-2d6a15a83a24">
