### ISSUE TITLE
“冒”系列字符不统一/使用日本写法

### ISSUE THREAD

**Issue by NightFurySL2001** [justfont/open-huninn-font#13]
“冒”系列应该上面从⺜，而 ”冒“ ”帽“ 仍旧依照日本写法从 ”日“，应该修改。
![image](https://user-images.githubusercontent.com/33471049/82005860-1255d880-9699-11ea-9cff-fea138035e98.png)

**Comment by NightFurySL2001** [comment]
【题外话：[糖圆体](https://github.com/NightFurySL2001/TangYuan-font)已经修复此问题。】

**Comment by rutopio** [comment]
謝謝您告訴我們，我們會在未來的新版本中修正。

It will be fixed in our upcoming version soon, thank you.

**Comment by rutopio** [comment]
`冒` 偏旁的字符已於 `2.0` 版本中統一部件。

<img width="1043" alt="image" src="https://github.com/user-attachments/assets/af8ffdb8-28a1-4025-bc3c-761a5faffd13">
