### ISSUE TITLE
造字許願池 - 缺少教育部重編國語辭典修訂本「瑿」字型

### ISSUE THREAD

**Issue by Sakamoto-Blog** [justfont/open-huninn-font#14]
Dear

缺少教育部重編國語辭典修訂本 **「瑿」** 字型，是否可以加入 **「瑿」** 缺字？

Many Thanks

**Comment by Sakamoto-Blog** [comment]
移到 [https://github.com/justfont/open-huninn-font/issues/2](https://github.com/justfont/open-huninn-font/issues/2) 集中文

**Comment by rutopio** [comment]
`瑿` 字已於 `2.1` 版本中新增。

<img width="1150" alt="image" src="https://github.com/user-attachments/assets/630569a3-fbbe-4c04-99de-a56fc2a44338">
