### ISSUE TITLE
「脅」字的粗體有問題

### ISSUE THREAD

**Issue by MuTsunTsai** [justfont/open-huninn-font#15]
![2020-04-26 19 34 22](https://user-images.githubusercontent.com/39870664/80306306-1e1a5180-87f5-11ea-8838-4a14a19f54e1.png)
參見圖片例子

**Comment by NightFurySL2001** [comment]
粉圆并无粗体，但是 [假粉圆体](https://github.com/max32002/FakePearl) 的确有提到这个字的外框线方向错误并提交bug，粉圆应该已经于1.10版修正。

**Comment by MuTsunTsai** [comment]
原來如此，我並不知道有 1.1 版，已經確認修正了，感謝。
