### ISSUE TITLE
字形不一致

### ISSUE THREAD

**Issue by Marcus98T** [justfont/open-huninn-font#16]
"闥"有bug
"舗襯"部件不一致
![Annotation 2020-05-09 174951](https://user-images.githubusercontent.com/10541683/81470515-b533d000-921d-11ea-82ad-896b03987be9.png)
這些字形有日本新字形，其他相似字形是舊的。
"寳"（應該是 "尔"，不是 "尓"）
"喰食飧養餐餮饕饗饜"（"餮饕" 是舊部，食部應該是橫，不是豎）
"麻麿痳"（其他 "麻" 部是舊部）
![Annotation 2020-05-09 175638](https://user-images.githubusercontent.com/10541683/81470655-73575980-921e-11ea-96a6-9ccb7af885d6.png)

**Comment by rutopio** [comment]
謝謝您告訴我們，我們會在未來的新版本中修正。

It will be fixed in our upcoming version soon, thank you.

**Comment by rutopio** [comment]
- `食` 部件的字符已於 `2.0` 版本中統一。

<img width="1150" alt="image" src="https://github.com/user-attachments/assets/0dc1a4f1-5ab9-4415-9855-be5e29344c26">

- `麻` 部件的字符已於 `2.1` 版本中統一。

<img width="1150" alt="image" src="https://github.com/user-attachments/assets/70cdf13e-0e82-4b61-9601-249c243117b2">

- `亲` 部件的字符已於 `2.1` 版本中統一。

<img width="1150" alt="image" src="https://github.com/user-attachments/assets/617060f1-dc41-4b50-8782-a97517b9d450">
