### ISSUE TITLE
U+771F 真 的設計

### ISSUE THREAD

**Issue by c933103** [justfont/open-huninn-font#18]
現在 U+771F 和其他有用相同部件的字，設計上都是和 U+771E 眞 一樣的。為了區分相關字形以及符合慣用字形，是否修改相關字形設計比較好？

**Comment by nodegin** [comment]
我覺得這套字體是儘可能使用傳統寫法
可是如果「真」是「眞」的話
「為」也應該是「爲」
「青」也應該是「靑」
「羽」也應該是「羽」
希望以後能更新一下

**Comment by i-font** [comment]
這字體使用了基礎的傳承字形為部分漢字的基礎，在傳統印刷字形中，長期以來都作「眞」形，不會區分作兩個字符。反而是Unicode編碼時考慮着別的條件，沒有充分照顧傳承字形的需求。

基於輸入法所限，許多人一般情況下都只能打出 U+771F ，不能打出 U+771E 。要是我們不把 U+771F 製作成「眞」形，無異於違背了傳承字形的需求。因此我不認爲需要修改。而同樣道理， nodegin 所提出的例子，我認爲都最好能採用傳統印刷字形的寫法。

**Comment by UltimateAmitieKaiNiC** [comment]
還有驟的右邊「聚」怎麼不改呢？

**Comment by rutopio** [comment]
此為原本小杉圓體的特色，在粉圓體中我們決定保持原樣。

不過，本專案以 OFL 開源授權釋出，若您對該部分的筆形有調整的需求，您可以自由下載、改作、發布，無需特別知會。
