### ISSUE TITLE
𩙿/飠偏旁

### ISSUE THREAD

**Issue by c933103** [justfont/open-huninn-font#19]
感覺上飠比較配合現代中文書寫習慣
(兼容區等字除外)

**Comment by nodegin** [comment]
這套字體是以傳統寫法，神字也是示不是ネ旁。

**Comment by SyaoranHinata** [comment]
反對。印刷字形的需求和特點，本質上就不同於手寫字。「飠部件」是傳承字形，符合多年來的印刷習慣，至今仍天天在身邊出現。沒有理由強行以楷體律圓體，破壞字型的美觀。

**Comment by max32002** [comment]
參考看看「台灣粉圓」
https://github.com/max32002/TaiwanPearl

**Comment by SyaoranHinata** [comment]
要說意見的話，我個人是強烈認爲所謂「台灣粉圓」的做法非常不可取。那些左右偏旁位置不呼應的撕裂、筆畫跳躍、中宮問題等等，嚴重刺激眼球，在正常的閱讀過程中帶來無比干擾。
我只可以說，樓上的朋友要這樣做，我「吹你唔脹」（奈你不何），不能干涉你的權利，閣下自有運用時間的自由。但在排印需求上，這成品絕對不是可取的、符合需求的字形。

**Comment by rutopio** [comment]
此為原本小杉圓體的特色，在粉圓體中我們決定保持原樣。

不過，本專案以 OFL 開源授權釋出，若您對該部分的筆形有調整的需求，您可以自由下載、改作、發布，無需特別知會。
