### ISSUE TITLE
缺字許願池

### ISSUE THREAD

**Issue by ButTaiwan** [justfont/open-huninn-font#2]
涔

**Comment by rschiang** [comment]
剛剛試了 `◢▆▅▄▃崩╰(〒皿〒)╯潰▃▄▅▇◣` 也是。XD

**Comment by chlbc** [comment]
元素週期表缺字：
氬鈧釩鎵銣鍶釔鈮鉬鎝釕銠鈀銦碲銫鑭鈰鐠釹鉕銪釓鋱鈥鉺銩鐿鎦鉿鉭鋨銥鉍釙砈氡鍅𨧀𨭎𨨏𨭆䥑鐽錀鎶鉨鈇鏌鉝鿬鿫

**Comment by chlbc** [comment]
破折號 TWO-EM DASH（U+2E3A）：⸺

**Comment by max32002** [comment]
丢 (U+4e22)
呐 (U+5450)
术 (U+672f)
殁 (U+6b81)
蜕 (U+8715)
傌 (U+508c)
曱 (U+66f1)
兀 (U+fa0c)

**Comment by shuwn** [comment]
好棒的字體！
可惜在 Mac 下的預覽顯示還有缺字，要是能補全就更完美了❤️
![Snipaste_2020-03-17_10-01-56](https://user-images.githubusercontent.com/20023822/76814981-4ba7ce80-6837-11ea-9efb-a6977b12714c.jpg)

**Comment by nodegin** [comment]
可否增加對香港常用字的支持
比如說：「嘅」「噉」「咗」「嘢」等

**Comment by Hulenkius** [comment]
假如我想要「𰻞」(biang)字會不會有點冒犯設計師的意思😂😂

**Comment by Sakamoto-Blog** [comment]
缺少教育部重編國語辭典修訂本 「瑿」 字型，是否可以加入 「瑿」 缺字？

**Comment by ewjy** [comment]
缺少台語和客語漢字，如：
𠢕（台語gâu）
𠊎（客語【亻厓】ngài）
希望能補上。

**Comment by nodegin** [comment]
有檯無枱

**Comment by gwowg** [comment]
员

**Comment by c933103** [comment]
U+0030 U+FE00 0̸ 有斜劃的零（Variation Selector）
U+20BF ₿ BITCOIN符號
U+20DD ⃝   組合內嵌圓形
U+20DE ⃞  組合內嵌方形
U+2109 ℉ 華氏符號
U+210F ℏ
U+212F ℯ
U+2153 ⅓ 三分之一
U+2154 ⅔ 三分之二
U+2194 ↔ 左右雙向箭嘴
U+2195 ↕ 上下雙向箭嘴
U+274C ❌ 叉號
U+2A7D ⩽ 下劃線斜着的小於符號 
U+2A7E ⩾ 下劃線斜着的大於符號
----
U+5151 兑
U+543F 吿
U+5497 咗 粵語字
U+54CB 哋 粵語字
U+551E 唞 粵語字
U+55CC 嗌 粵語字
U+55F0 嗰 粵語字
U+5605 嘅 粵語字
U+5622 嘢 粵語字
U+5625 嘥 粵語字
U+5649 噉 粵語字
U+56BF 嚿 粵語字
U+58BC 墼
U+57D7 埗 香港地名用字
U+5A33 娳 人名用字
U+5A38 娸 人名用字
U+5B7B 孻 粵語字
U+5C10 尐 粵語字
U+6207 戇 粵語較常用字
U+6237 户
U+6286 抆 粵語字
U+6423 搣 粵語字
U+64BE 撾 國際地名用字
U+6530 攰 粵語字
U+65EE 旮
U+65EF 旯
U+65FC 旼 人名用字
U+6621 昡
U+6C0A 氊
U+6C15 氕 化學用字
U+6C18 氘 化學用字
U+6C1A 氚 化學用字
U+6C21 氡 化學用字
U+6C2C 氬 化學用字
U+6C39 氹 澳門地名用字
U+6C3D 氽 粵語字
U+6F99 澙 地名用字
U+71D3 燓 人名用字
U+71E1 燡 人名用字
U+727F 牿
U+7534 甴 粵語字
U+7540 畀 粵語字
U+7F97 羗 異體字
U+913A 鄺 人名用字
U+9962 饢

**Comment by hsuan1117** [comment]
我的名字
玹

**Comment by NightFurySL2001** [comment]
Big5 常用汉字（5401字）缺字：
`伋刖圩汛汍抆杗沔沘阬佺劻姅枓泜泖泠秈芣芰芾邶帟枰柙洹洧洮洎畎疢耑虺觔郃屘敉晅栘涊浥涔砟蚜訏訑釙陘偯偭啁屝崤敔梡梂涪涿笮紱脰脤訢釩雩堠嵇愒氬湩琯絰菔蛐詖郾鈇隄僇嗉暍楛溧睢硿裒覜詻訾詨跦鄗鉍雊髡僎僩劂嘐塽摭榦榣瑭箄裯遝鄘鄞酴鉼雒儅勰墦奭嶔撙撢撳潠箠緙膘褕誶賡踡輞輥頫劓撾氅澶澦澠澴璘瘺穋翮蕞褡豭鄴錕壎屨擭歜毚濩糝縴繈縿縯褽豳賸鍚燸韹鯈儳譆櫬騵瓖羼觼酈欐瓚籣臢鑤灞鱟韉讜釅`

**Comment by rutopio** [comment]
> U+0030 U+FE00 0̸ 有斜劃的零（Variation Selector） U+20BF ₿ BITCOIN符號 U+20DD ⃝ 組合內嵌圓形 U+20DE ⃞ 組合內嵌方形 U+2109 ℉ 華氏符號 U+210F ℏ U+212F ℯ U+2153 ⅓ 三分之一 U+2154 ⅔ 三分之二 U+2194 ↔ 左右雙向箭嘴 U+2195 ↕ 上下雙向箭嘴 U+274C ❌ 叉號 U+2A7D ⩽ 下劃線斜着的小於等於符號 U+2A7E ⩾ 下劃線斜着的大於等於符號
> 
> U+5151 兑 U+543F 吿 U+5497 咗 粵語字 U+54CB 哋 粵語字 U+551E 唞 粵語字 U+5571 啱 粵語字 U+55CC 嗌 粵語字 U+55F0 嗰 粵語字 U+5605 嘅 粵語字 U+5622 嘢 粵語字 U+5625 嘥 粵語字 U+5649 噉 粵語字 U+56A4 嚤 粵語字 U+56BF 嚿 粵語字 U+58BC 墼 U+57D7 埗 香港地名用字 U+57DE 埞 粵語字 U+5A33 娳 人名用字 U+5A38 娸 人名用字 U+5B7B 孻 粵語字 U+5C10 尐 粵語字 U+6207 戇 粵語較常用字 U+6237 户 U+6286 抆 粵語字 U+6423 搣 粵語字 U+64BE 撾 國際地名用字 U+6530 攰 粵語字 U+65EE 旮 U+65EF 旯 U+65FC 旼 人名用字 U+6621 昡 U+66F1 曱 粵語字 U+6C0A 氊 U+6C15 氕 化學用字 U+6C18 氘 化學用字 U+6C1A 氚 化學用字 U+6C21 氡 化學用字 U+6C2C 氬 化學用字 U+6C39 氹 澳門地名用字 U+6C3D 氽 粵語字 U+6F99 澙 地名用字 U+71D3 燓 人名用字 U+71E1 燡 人名用字 U+727F 牿 U+7534 甴 粵語字 U+7540 畀 粵語字 U+777A 睺 粵語字 U+7F97 羗 異體字 U+913A 鄺 人名用字 U+93F9 鏹 粵語字 U+9962 饢 U+9AB9 骹 粵語字 U+9C02 鰂 香港地名用字
> 
> U+20C41 𠱁 粵語字 U+20F4C 𠽌 粵語字 U+210C1 𡃁 粵語字 U+210E4 𡃤 粵語字 U+22C51 𢱑 粵語字

很抱歉，粉圓體主要收錄臺灣常用漢字及臺客語用字，目前並無增補粵語字的計畫。

**Comment by rutopio** [comment]
至於其他的缺字許願，我們會在進行評估後，考慮於未來的新版本中陸續增補。

**Comment by rutopio** [comment]
> 涔

`涔` 字已於 2.0 版本中新增。

<img width="1043" alt="image" src="https://github.com/user-attachments/assets/2a6abb8f-ef20-49b8-8074-404e89cb624f">

**Comment by rutopio** [comment]
> ◢▆▅▄▃崩╰(〒皿〒)╯潰▃▄▅▇◣

`◢▆▅▄▃╰╯▃▄▅▇◣` 字已於 `2.1` 版本中新增。

<img width="1183" alt="image" src="https://github.com/user-attachments/assets/edb2564e-4441-4f8a-a468-d891829f5297">

**Comment by rutopio** [comment]
> 氬鈧釩鎵銣鍶釔鈮鉬鎝釕銠鈀銦碲銫鑭鈰鐠釹鉕銪釓鋱鈥鉺銩鐿鎦鉿鉭鋨銥鉍釙砈氡鍅𨧀𨭎𨨏𨭆䥑鐽錀鎶鉨鈇鏌鉝鿬鿫

`氬鈧釩鎵銣鍶釔鈮鉬鎝釕銠鈀銦碲銫鑭鈰鐠釹鉕銪釓鋱鈥鉺銩鐿鎦鉿鉭鋨銥鉍釙砈氡鍅𨧀𨭎𨨏𨭆䥑鐽錀鎶鉨鈇鏌鉝鿬鿫` 等元素週期表用字已陸續於 `2.0` 及 `2.1` 版本中新增。

<img width="1014" alt="image" src="https://github.com/user-attachments/assets/ae57a86f-7557-4a80-9ed8-c522a875fa43">

**Comment by rutopio** [comment]
> 破折號 TWO-EM DASH（U+2E3A）：⸺

`⸺` 已於 `2.1` 版本中新增。

**Comment by rutopio** [comment]
> 丢 (U+4e22) 呐 (U+5450) 术 (U+672f) 殁 (U+6b81) 蜕 (U+8715) 傌 (U+508c) 曱 (U+66f1) 兀 (U+fa0c)

`丢呐术殁蜕傌曱兀` 已陸續於 `2.0` 及 `2.1` 版本中新增。

<img width="652" alt="image" src="https://github.com/user-attachments/assets/ee3b9721-b235-413c-b658-53efb97e93b0">

**Comment by rutopio** [comment]
> 可否增加對香港常用字的支持 比如說：「嘅」「噉」「咗」「嘢」等

`嘅噉咗嘢` 已於 `2.0` 版本中新增。

<img width="776" alt="image" src="https://github.com/user-attachments/assets/09a22b7e-42c0-4fbd-82de-1866a663973f">

**Comment by rutopio** [comment]
> 有臺有台有檯無枱

`𠢕𠊎` 已於 `1.1` 版本中新增。

<img width="776" alt="image" src="https://github.com/user-attachments/assets/10176407-bc8a-43ca-9ec4-27cb70654dfe">

**Comment by rutopio** [comment]
> 缺少台語和客語漢字，如： 𠢕（台語gâu） 𠊎（客語【亻厓】ngài） 希望能補上。

`𠢕𠊎` 已於 `1.1` 版本中新增。

<img width="776" alt="image" src="https://github.com/user-attachments/assets/10176407-bc8a-43ca-9ec4-27cb70654dfe">

**Comment by rutopio** [comment]
> 有臺有台有檯無枱

`枱` 已於 `2.0` 版本中新增。

<img width="1013" alt="image" src="https://github.com/user-attachments/assets/e0b1443e-314b-4cac-9aa3-e25326c82efb">

**Comment by rutopio** [comment]
> U+0030 U+FE00 0̸ 有斜劃的零（Variation Selector） U+20BF ₿ BITCOIN符號 U+20DD ⃝ 組合內嵌圓形 U+20DE ⃞ 組合內嵌方形 U+2109 ℉ 華氏符號 U+210F ℏ U+212F ℯ U+2153 ⅓ 三分之一 U+2154 ⅔ 三分之二 U+2194 ↔ 左右雙向箭嘴 U+2195 ↕ 上下雙向箭嘴 U+274C ❌ 叉號 U+2A7D ⩽ 下劃線斜着的小於等於符號 U+2A7E ⩾ 下劃線斜着的大於等於符號
> 
> U+5151 兑 U+543F 吿 U+5497 咗 粵語字 U+54CB 哋 粵語字 U+551E 唞 粵語字 U+5571 啱 粵語字 U+55CC 嗌 粵語字 U+55F0 嗰 粵語字 U+5605 嘅 粵語字 U+5622 嘢 粵語字 U+5625 嘥 粵語字 U+5649 噉 粵語字 U+56A4 嚤 粵語字 U+56BF 嚿 粵語字 U+58BC 墼 U+57D7 埗 香港地名用字 U+57DE 埞 粵語字 U+5A33 娳 人名用字 U+5A38 娸 人名用字 U+5B7B 孻 粵語字 U+5C10 尐 粵語字 U+6207 戇 粵語較常用字 U+6237 户 U+6286 抆 粵語字 U+6423 搣 粵語字 U+64BE 撾 國際地名用字 U+6530 攰 粵語字 U+65EE 旮 U+65EF 旯 U+65FC 旼 人名用字 U+6621 昡 U+66F1 曱 粵語字 U+6C0A 氊 U+6C15 氕 化學用字 U+6C18 氘 化學用字 U+6C1A 氚 化學用字 U+6C21 氡 化學用字 U+6C2C 氬 化學用字 U+6C39 氹 澳門地名用字 U+6C3D 氽 粵語字 U+6F99 澙 地名用字 U+71D3 燓 人名用字 U+71E1 燡 人名用字 U+727F 牿 U+7534 甴 粵語字 U+7540 畀 粵語字 U+777A 睺 粵語字 U+7F97 羗 異體字 U+913A 鄺 人名用字 U+93F9 鏹 粵語字 U+9962 饢 U+9AB9 骹 粵語字 U+9C02 鰂 香港地名用字
> 
> U+20C41 𠱁 粵語字 U+20F4C 𠽌 粵語字 U+210C1 𡃁 粵語字 U+210E4 𡃤 粵語字 U+22C51 𢱑 粵語字

提及的字符皆已陸續於 `2.0` 及 `2.1` 版本中新增。

<img width="973" alt="image" src="https://github.com/user-attachments/assets/51704783-741a-4bad-a763-4d70bca0f19e">

<img width="973" alt="image" src="https://github.com/user-attachments/assets/3705f217-dc85-445e-b5af-03bc4f7dcd7e">

<img width="973" alt="image" src="https://github.com/user-attachments/assets/5e982e6a-2dd1-4719-a4e4-5bfe7e9920f9">

<img width="973" alt="image" src="https://github.com/user-attachments/assets/b115ccfe-6370-4fb1-a2cd-fa6c44413c0a">
