### ISSUE TITLE
部件 巨 設計不統一的問題

### ISSUE THREAD

**Issue by c933103** [justfont/open-huninn-font#20]
詳見 https://github.com/justfont/open-huninn-font/issues/20#issuecomment-628991114 和 https://github.com/justfont/open-huninn-font/issues/20#issuecomment-633126323

**Comment by NightFurySL2001** [comment]
“巨” 应当从 “工”，符合字理，并无不妥，因此无需修改。

同系列里面的 “渠” 倒是没有从 “工”， 应该修改。

![image](https://user-images.githubusercontent.com/33471049/82005265-7c6d7e00-9697-11ea-8d00-1233aaa05190.png)

**Comment by nodegin** [comment]
巨 也是沒有，應該要更新

**Comment by rutopio** [comment]
謝謝您告訴我們，我們會在未來的新版本中修正。

It will be fixed in our upcoming version soon, thank you.

**Comment by rutopio** [comment]
`巨` 偏旁的字符已於 `2.0` 版本中統一。

<img width="1068" alt="image" src="https://github.com/user-attachments/assets/8b9f7c98-1ef6-427b-8ff3-b69198457d7b">
