### ISSUE TITLE
U+9824 (頤) 字形错误

### ISSUE THREAD

**Issue by NightFurySL2001** [justfont/open-huninn-font#21]
U+9824 (頤) 在粉圆内显示为 U+9823 (頣)，而U+9823无字。

![image](https://user-images.githubusercontent.com/33471049/82006412-539ab800-969a-11ea-8db8-72eae2739082.png)

**Comment by rutopio** [comment]
謝謝您告訴我們，我們會在未來的新版本中修正。

It will be fixed in our upcoming version soon, thank you.

**Comment by rutopio** [comment]
U+9824 (`頤`) 與 U+9823 (`頣`) 已於 2.0 版本中分開編碼。

<img width="990" alt="image" src="https://github.com/user-attachments/assets/944c1fa1-bbca-4f1d-839c-cdf3406ee624">
