### ISSUE TITLE
中文字寬度=1000，寬度不是 1024

### ISSUE THREAD

**Issue by max32002** [justfont/open-huninn-font#22]
例如: 㐁㑁㓾㔂㕸㖅㖸㗘㗱㘔㘛㘝㜮㜷㝗㝩㤉㤕㧁㧌㧎㧒㧡㧣㧻㧾㨂㨑㨨㨪㨻㩆㪐㬹㰵㴘㴙㷮㸐㸰㼓㽎㾀㾊㿸䀐䀯䀴䁯䃗䆀䇶䈄䉂䌈䖙䖳䗁䗆䗐䘆䘥䘼䞚䟓䟘䟩䠡䢍䢢䫌䯋䲅亼伨倈倲傪僫凃凴刣剾勥匧叹吂吓吔哊哯哹唩唿啉啲喺嗬噍噼嚟圝坔塠壠奒媠嫲廍抅抐抺拁挱挵挷捒捝捾揞揢揬揻搙搝搩摖摱撆撍撨攋攑敋敱杮桊梘槺橂檫溚漖灇炣烌煏熻燶疴癀眡砄砛硓秥稴竳竵篼粩糍絚繏羓羴肨胮胿腈膁膎膭臁臽蕒蕳藠虬蝲螕蟎蟮蠘襀襇誐贌跔踭蹽躼軁递逩鈪錑閕靗頕魩鮊鮘鯮鱲黗𠊎𠎷𠕆𠕇𠖄𠗻𠜱𠞩𠞭𠠃𠠝𠢕𠯗𠲿𡢃𡳞𢎙𢪱𢫦𢯭𢯾𢱤𢲴𢲸𢳆𢳪𢶀𢼌𢼛𣁳𣛮𣮈𣲩𣻸𣼎𤉙𤊶𤌍𤍒𤐙𤐰𤘅𤞚𤲍𤶃𤸁𤸱𤺅𤺪𥉌𥌚𥍉𥐵𥑮𥯟𥯥𥰔𥴊𥺆𦉎𦊓𦜆𦟪𧉟𧊅𧌄𧩣𧮙𧻴𧿬𧿳𨂾𨂿𨃰𨅔𨒇𨢑𩑾𩚨𩛩𩜄𩜰𩵱𩸙𩸶𩼧𪁎𪐞𪖐𪘒𪜶𪹚𫝏𫝘𫝛𫝺𫝻𫞼𫟂𫟧𫠛𫣆𬠖𬦰𰣻𰹬

**Comment by NightFurySL2001** [comment]
诶？这些字看起来是1.001新增的413个台语字吧？我补字时也发现这些有点问题

**Comment by rutopio** [comment]
謝謝您告訴我們，我們會在未來的新版本中修正。

It will be fixed in our upcoming version soon, thank you.
