### ISSUE TITLE
戾系列错误/仍旧日本标准

### ISSUE THREAD

**Issue by NightFurySL2001** [justfont/open-huninn-font#23]
綟仍旧日本标准，錑应该是错字了(?)。

![image](https://user-images.githubusercontent.com/33471049/85120235-8ca7e880-b255-11ea-8d52-80b629621044.png)

**Comment by UltimateAmitieKaiNiC** [comment]
那麼這個字體的戶為什麼不是日本字形？這個戸才是日本字形。標著戶字的偏旁是日本字形呀！

**Comment by NightFurySL2001** [comment]
@UltimateAmitieKaiNiC 好问题。看起来是justfont把戶与戸分开字形的。可能是考虑到户戶戸在unicode内是分开编码的原因，为了避免混淆，故意分开。（但是这个就跟 真 的情况不同..... 参考 #18 ，这里justfont对这个字体的设计取舍有点奇怪。）
![image](https://user-images.githubusercontent.com/33471049/85913411-24fe2880-b867-11ea-833e-4d9158ea30c2.png)
（上小杉圆体，中粉圆，下思源台标）

P/S: 魲 在原字体内就已经是戶形了，不太确定 戶 是不是从 魲 取的字形…

**Comment by rutopio** [comment]
謝謝您告訴我們，我們會在未來的新版本中修正。

It will be fixed in our upcoming version soon, thank you.

**Comment by rutopio** [comment]
`戾` 偏旁的字符已於 `2.0` 版本中統一。

<img width="990" alt="image" src="https://github.com/user-attachments/assets/c749dfac-83cc-4546-a7d5-cd0eb76709f9">
