### ISSUE TITLE
將粉圓提交到 Google Fonts，方便大眾使用，並提升字型能見度

### ISSUE THREAD

**Issue by tan9** [justfont/open-huninn-font#24]
依據 https://github.com/google/fonts/blob/master/CONTRIBUTING.md#new-families 的說明，將 open 粉圓提交到 Google Fonts 上，讓更多人可以更方便的使用「jf open 粉圓字型」。

順便充實一下 Google Fonts 正體中文清單: https://fonts.google.com/?subset=chinese-traditional
不然現在只有 Noto Sans TC, Noto Serif TC，看起來很虛弱。

**Comment by medicalwei** [comment]
卡在 Reserved Font Names 這件事情，因為粉圓 derived 的字體有使用到，所以基本上不可行

**Comment by tan9** [comment]
@medicalwei 或許可以直接在 https://github.com/avrahamcornfeld/Varela-Round-Hebrew 裡問問原作者??

**Comment by NightFurySL2001** [comment]
问题：据justfont宣传，西文Varela Round也是从Google Fonts找出来的（[这里](https://fonts.google.com/specimen/Varela+Round)），虽然有RFN但是还是上得了Google Fonts。这情况可以参考吗？

**Comment by rutopio** [comment]
目前我們沒有提交給 Google Font 的計畫。
