### ISSUE TITLE
可以把英文字母"g"的descent調低一點嗎?

### ISSUE THREAD

**Issue by hellokoman** [justfont/open-huninn-font#25]
<img width="822" alt="Screenshot 2020-08-08 at 4 38 02 AM" src="https://user-images.githubusercontent.com/5645504/89686503-1492a080-d931-11ea-8ffb-ff9696b712c0.png">

因為Descent不足以覆蓋整個字母, 顯示時容易會被忽略了應有的高度

下方是錯誤的示範
<img width="534" alt="Screenshot 2020-08-08 at 4 40 44 AM" src="https://user-images.githubusercontent.com/5645504/89686669-59b6d280-d931-11ea-9f18-e1017bc02125.png">

**Comment by rutopio** [comment]
謝謝您告訴我們，我們會在未來的新版本中修正。

It will be fixed in our upcoming version soon, thank you.
