### ISSUE TITLE
“朵”系列部分汉字设计奇怪

### ISSUE THREAD

**Issue by NightFurySL2001** [justfont/open-huninn-font#27]
“剁” “跺” 二字的设计视觉上有点奇怪
![image](https://user-images.githubusercontent.com/33471049/92231237-065b8400-eedf-11ea-88b3-a3dae5a237a1.png)
![image](https://user-images.githubusercontent.com/33471049/92231353-30ad4180-eedf-11ea-8102-589497a916db.png)

**Comment by rutopio** [comment]
此為原本小杉圓體的特色，在粉圓體中我們決定保持原樣。

不過，本專案以 OFL 開源授權釋出，若您對該部分的筆形有調整的需求，您可以自由下載、改作、發布，無需特別知會。

**Comment by NightFurySL2001** [comment]
@rutopio 恕无法接受“保持原样”的说法。小杉圆体并未有 “剁” “跺” 二字，是由 justfont 人员新增的。请参考下图。“躲” 字（也是 justfont 新增）的比例相对比较正常。

![image](https://user-images.githubusercontent.com/33471049/216358949-56007425-d932-4330-b9b8-85445e5c7d8c.png)

**Comment by rutopio** [comment]
您好，上述留言所指稱之「保持原樣」，係指和小杉圓體中的「朵」字之筆頭與造型保持一致。

至於您所稱的比例問題，我們會再跟設計師們討論是否修改，謝謝您的 feedback。

**Comment by rutopio** [comment]
`朵` 偏旁的字符已於 2.0 版本中修正並統一部件。

<img width="1043" alt="image" src="https://github.com/user-attachments/assets/838d24b5-9da4-400a-a5dd-2b9603c7ec33">
