### ISSUE TITLE
漢字字身框下潛，不相容小杉圓體/金萱/金萱那提等等

### ISSUE THREAD

**Issue by RuixiZhang42** [justfont/open-huninn-font#28]
小杉圓體中的漢字字身框是1024×1024，底部在-123，頂部在901，下降比上升約12%比88%

這種分配字身框的方式似乎是絕大多數日文字型的標準做法，如果字型是OpenType，那麼字身框是1000×1000，底部在-120，頂部在880。金萱、金萱那提、思源系列，全部都是這個規格。

但是不知為何「jf open 粉圓」改變了小杉圓體中的原本設定，變成底部在-153，頂部在871，下降比上升變成約15%比85%，這樣跟別的字型混排，就會顯得粉圓基線下潛。

**Comment by KrasnayaPloshchad** [comment]
建議在該字型中引入 [`base`](https://docs.microsoft.com/en-us/typography/opentype/spec/base) 表格，如果將漢字字身框資訊加入其中，那麼這個表會允許軟體根據這個表的資訊對齊字元，並根據需要將字元上抬或下潛。

**Comment by rutopio** [comment]
謝謝您告訴我們，我們會在未來的新版本中修正。

It will be fixed in our upcoming version soon, thank you.
