### ISSUE TITLE
台語白話字缺少 ᶰ

### ISSUE THREAD

**Issue by cathree3** [justfont/open-huninn-font#29]
希望可以補充 ⁿ 的大寫版本 ᶰ ᴺ，謝謝
<img width="711" alt="QQ20200911-114732@2x" src="https://user-images.githubusercontent.com/13507992/92855370-c6d3f100-f424-11ea-812c-41ddd0c7f928.png">

**Comment by rutopio** [comment]
大小寫都有做，碼位位置如下：

- ⁿ (U+207F, nmod)
- ᴺ (U+1D3A, Nmod)
