### ISSUE TITLE
Can we remove the version suffix of PostScript name?

### ISSUE THREAD

**Issue by toto-minai** [justfont/open-huninn-font#3]
If there is going to be an update, it'll cause less problem when using your font in code 😊.

**Comment by bestpika** [comment]
拜託官方把那個版本號移除，不然每次更新都要去改一大堆設定才能使用正確的版本

**Comment by tasi788** [comment]
自己本身有把粉圓用於其他開源專案上，結果完整名稱卻有版本號實在是很不方便。  
而 `TrueType` 本身就支援了版本的標籤，在釋出的檔案中也有看見標示的版本號(如下圖)  

![image](https://user-images.githubusercontent.com/11913223/79723219-f53b1d80-8317-11ea-834f-2e9c6416aace.png)  
因此我認為實在是沒有必要將版本號強塞到名稱內。  
## Ref: 
https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=IWS-Chapter08

**Comment by miggo** [comment]
字型檔名以及 postname 的差異，主要考慮到一般使用者使用的狀況，有以下幾個考量：
1. 希望使用者安裝時不要覆蓋到舊的版本，因此檔名本身會帶到版本號，避免覆蓋。
2. 安裝後，不會影響到舊的的設計和排版（例如 baseline / 空格或是 line height 變更，都會影響到原本舊的排版格式），因此在安裝後的字型檔名會帶出版本號，避免因為字型檔案更新，影響到舊的文件。

如果都採用相同的名稱，的確會適合程式的使用，
但對於一般使用者或設計師而言，安裝新的字型檔案，
造成既有的排版跑掉，會造成很大的困擾，
以上說明也讓您知道我們的這種設計的原因，謝謝大家！

**Comment by bufhdy** [comment]
However, you may keep old versions what they were and get rid of the suffix of the latest one. People can choose to use a certain version if they wish to while others can just keep the font up-to-date and enjoy the new version without dealing with the name problem 😖.

**Comment by bestpika** [comment]
@miggo 所以你們就不能乾脆釋出一種有版本的一種沒版本的檔案嗎？

**Comment by miggo** [comment]
或許這樣的描述會更清楚，實際的使用狀況是：例如我用 「jf open 粉圓」名稱安裝 1.0 版，使用了一個月編輯了許多文件；但 1.1 版本中變更了預設行高，檔名如果相同為  「jf open 粉圓」，在安裝後會直接覆蓋原本字型，會發生原本使用粉圓的所有文件，行高都不一樣了！
要避免這樣的事情，只能在檔名部分做差異。

**Comment by bestpika** [comment]
@miggo 我是不懂「要用舊版本」的設計師去安裝新版本的用意啦

**Comment by miggo** [comment]
> @miggo 所以你們就不能乾脆釋出一種有版本的一種沒版本的檔案嗎？
這是我們在字型檔名設定的規則，因粉圓是開源字型，非常歡迎 fork 自己做變更喔！

**Comment by miggo** [comment]
> @miggo 我是不懂「要用舊版本」的設計師去安裝新版本的用意啦

不是設計師用舊版字型，是避免「新版字型」覆蓋掉舊版字型導致的問題

**Comment by bestpika** [comment]
請問 Adobe 裡的字型有把版本放在字型名稱內嗎？

**Comment by miggo** [comment]
> 請問 Adobe 裡的字型有把版本放在字型名稱內嗎？

沒有喔，如果不常常更新字型的確不用帶版本號。

**Comment by miggo** [comment]
> 請問 Adobe 裡的字型有把版本放在字型名稱內嗎？

如果確定不會改版，的確可以不帶版本號的。

**Comment by bestpika** [comment]
> > @miggo 所以你們就不能乾脆釋出一種有版本的一種沒版本的檔案嗎？
> 這是我們在字型檔名設定的規則，因粉圓是開源字型，非常歡迎 fork 自己做變更喔！

等等，我們在講字型名稱你怎麼跟我字型檔名？

**Comment by tasi788** [comment]
> @miggo 所以你們就不能乾脆釋出一種有版本的一種沒版本的檔案嗎？

![image](https://user-images.githubusercontent.com/11913223/80063873-7806e700-8569-11ea-8865-31dc5bbc7fcf.png)

感謝開源ㄉ力量
https://github.com/tasi788/open-huninn-font/releases

**Comment by rutopio** [comment]
字體的 suffix 版本號在尋找字體的功能中有其必要性，並能在安裝新版本字體時避免原先的排版跑掉，因此仍會保留。

不過，本專案以 OFL 開源授權釋出，若您對命名部分有特殊需求，您可以自由下載、改作、發布，無需特別知會。
