### ISSUE TITLE
找bug字（误）

### ISSUE THREAD

**Issue by NightFurySL2001** [justfont/open-huninn-font#30]
胚（U+80DA），v1.10版内月的竖线没有对准。
![image](https://user-images.githubusercontent.com/33471049/95594200-36b5b580-0a7d-11eb-9496-2aee5aec7219.png)

闥（U+95E5），v1.10版内羊的第一个横线线没有对准。（ https://github.com/justfont/open-huninn-font/issues/16 ）
![image](https://user-images.githubusercontent.com/33471049/95594291-55b44780-0a7d-11eb-976e-a206269e24ea.png)

**Comment by NightFurySL2001** [comment]
遺（U+907A），v1.10版内上面中的横竖没有对齐。
![image](https://user-images.githubusercontent.com/33471049/120930286-35797d00-c71f-11eb-9efe-478f02c77896.png)

**Comment by NightFurySL2001** [comment]
贛（U+8D1B），v1.10版内"早"部件的横竖没有对齐。
![image](https://user-images.githubusercontent.com/33471049/121373581-c6e02d80-c971-11eb-965e-6997414ffd76.png)

P/S: 贛右上疑似错误部件，应当是夂不是攵。
![image](https://user-images.githubusercontent.com/33471049/121374166-41a94880-c972-11eb-9ca4-bd29a4684137.png)

**Comment by rutopio** [comment]
謝謝您告訴我們，我們會在未來的新版本中修正。

It will be fixed in our upcoming version soon, thank you.
