### ISSUE TITLE
日文 U+301C WAVE DASH 直排资讯丢失

### ISSUE THREAD

**Issue by NightFurySL2001** [justfont/open-huninn-font#31]
![image](https://user-images.githubusercontent.com/33471049/96143644-dcfa3300-0f35-11eb-96d1-f99cc2de692b.png)
上为小杉圆体，下为jf open粉圆。
右边直排可以看见 U+FF5E FULLWIDTH TILDE (～) 有直排版本，而 U+301C WAVE DASH (〜) 没有直排版本。

**Comment by rutopio** [comment]
謝謝您告訴我們，這個會在未來的新版本中修正。

It will be fixed in our upcoming version soon, thank you.
