### ISSUE TITLE
U+406F （䁯）错字

### ISSUE THREAD

**Issue by NightFurySL2001** [justfont/open-huninn-font#32]
![image](https://user-images.githubusercontent.com/33471049/120667417-0dd8a980-c4c0-11eb-9615-4cfb31be8569.png)

**Comment by akira02** [comment]
應該是Unicode跑掉可以修正成正確的，但不知道原本這個字的unicode是什麼、要放到哪XD（還是他其實根本就不存在？）

**Comment by rutopio** [comment]
謝謝您告訴我們，這個會在未來的新版本中修正。

It will be fixed in our upcoming version soon, thank you.

**Comment by rutopio** [comment]
`䁯` 已於 `2.0` 的版本中修正。

<img width="990" alt="image" src="https://github.com/user-attachments/assets/1d6a34dc-d678-4f7e-b071-83c4435a6f9f">
