### ISSUE TITLE
廣東話常用字

### ISSUE THREAD

**Issue by hoishing** [justfont/open-huninn-font#33]
hi~ 我是來自香港的用戶，有些廣東話的常用字，希望能加入，例如：

嘅响哋啩嘥㗎啫揸嗰

謝謝 :)

**Comment by rutopio** [comment]
很抱歉，粉圓體主要收錄臺灣常用漢字及臺客語用字，粵語用字並不在此範圍內。

不過，本專案以 OFL 開源授權釋出，若您對粵語或其他語系的造字有興趣，您可以自由下載、改作、發布，無需特別知會。

**Comment by hoishing** [comment]
了解, 謝謝~

**Comment by rutopio** [comment]
`嘅响哋啩嘥㗎啫揸嗰` 已於 `2.0` 的版本中支援。

<img width="990" alt="image" src="https://github.com/user-attachments/assets/9808c125-ac49-4374-98df-da1dd3fdc2f9">
