### ISSUE TITLE
字形不同

### ISSUE THREAD

**Issue by UltimateAmitieKaiNiC** [justfont/open-huninn-font#34]
「驟」的右部分「聚」不一樣，請修改！
![image](https://user-images.githubusercontent.com/67255901/99923049-dc439080-2d6e-11eb-8337-e5c03a809ea2.png)

**Comment by rutopio** [comment]
謝謝您告訴我們，我們會在未來的新版本中修正。

It will be fixed in our upcoming version soon, thank you.

**Comment by rutopio** [comment]
`驟` 字已於 `2.0` 版本中修正。

<img width="990" alt="image" src="https://github.com/user-attachments/assets/af083699-7598-4b9c-b64a-156d029a9620">
