### ISSUE TITLE
U+56E7 （囧）疑似错字

### ISSUE THREAD

**Issue by NightFurySL2001** [justfont/open-huninn-font#35]
![image](https://user-images.githubusercontent.com/33471049/119485360-8b4a3e80-bd89-11eb-865a-105612724e40.png)

**Comment by rutopio** [comment]
謝謝您告訴我們，我們會在未來的新版本中修正。

It will be fixed in our upcoming version soon, thank you.

**Comment by rutopio** [comment]
`囧` 字已於 `2.0` 版本中修正。

<img width="990" alt="image" src="https://github.com/user-attachments/assets/07cf2e04-a2b5-48ca-8619-02137e90c089">
