### ISSUE TITLE
是否有規劃放上 CDN?

### ISSUE THREAD

**Issue by aquastripe** [justfont/open-huninn-font#39]
今天發現這個開源字型，覺得非常漂亮，想要以 CDN 方式放上網站
不過似乎沒有 CDN 的使用方法

想詢問是否有考慮放上 CDN，例如 jsDelivr
謝謝！

**Comment by kayac-chang** [comment]
同意。希望也可以放到 [Google Font](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)

**Comment by hsuan1117** [comment]
> 今天發現這個開源字型，覺得非常漂亮，想要以 CDN 方式放上網站
> 不過似乎沒有 CDN 的使用方法
> 
> 想詢問是否有考慮放上 CDN，例如 jsDelivr
> 謝謝！

jsDelivr可以自己弄連結呀
https://cdn.jsdelivr.net/gh/justfont/open-huninn-font@master/font/jf-openhuninn-1.1.ttf
