### ISSUE TITLE
希望能釋出用於編輯的原始檔

### ISSUE THREAD

**Issue by medicalwei** [justfont/open-huninn-font#4]
因為我想要將 open 粉圓字體包入 Debian GNU/Linux，但是由於我們對自由軟體的執念，我們會希望從編輯用的原始碼格式（例如 .glyphs, .ufo 等）用字體編譯工具產生再上傳。Debian 目前有包一些字體工具可以從這些格式產生 ttf, otf, woff 等格式。
另外，提供原始碼的話，也能方便 jf 合併其他人提供的貢獻，希望貴社能夠釋出編輯用的原始檔以便貢獻者編輯。

**Comment by nodegin** [comment]
看來貴專案是放上GitHub就再沒打算釋出原始檔或發佈新版本的了。。。

**Comment by KrasnayaPloshchad** [comment]
Adobe Fonts 就這樣做過

**Comment by holishing** [comment]
請問這部分後來有進一步的回應嗎? 感謝

**Comment by brlin-tw** [comment]
以下內容已同步寄送至 [just@justfont.com](mailto:just@justfont.com)

主旨：Fwd: Re: 希望能釋出用於編輯的原始檔 · Issue #4 · justfont/open-huninn-font

---

致 Justfont：

無意貶低 Justfont 公司與貴司字型設計師們的努力，但是鄙人對於 @justfont 將「字型建構產物上傳到 GitHub」的動作對外稱為「字型開源」這件事情感到失望，以下列舉粉圓字型所引用的開源字型作為對照組：

* 「小杉圓體」的編輯用源碼：<https://github.com/avrahamcornfeld/Varela-Round-Hebrew/tree/master/sources>  
  後續源碼完善：<https://github.com/googlefonts/kosugi/commits/main/sources>
* 「Varela Round」的編輯用源碼：<https://github.com/avrahamcornfeld/Varela-Round-Hebrew/tree/master/sources>  
  後續源碼完善：<https://github.com/avrahamcornfeld/Varela-Round-Hebrew/commits/master/sources>

於貴司 《[免費的粉圓字體，要吃嗎？先看看粉圓的設計尬聊](https://blog.justfont.com/2020/02/huninn-preview/)》文章中提到：

> 庭：因為原本拿到的不是可以直接編輯筆畫的外框檔案，所以我們要用字型設計軟體 Glyphs 把已經合併的筆畫拆開，才可以調整筆畫的粗細。尤其撇筆最難拆。比如說「撩」右邊的第一個橫筆太粗，要把筆畫拆開來，才能單獨調整橫筆，也要保證撇與橫畫銜接的合理性。
>
> 榕：這樣子一個字可能要多花十幾秒在拆筆畫上，而且其實差不多就是要改所有的字（笑）而且我們兩人最後加起來共調整了 5000 多字，花費的功與時間是非常可觀的⋯⋯

鄙人非造字專業所以以下論述如有錯誤敬請見諒，但據我所知目前所「粉圓」釋出的字型文件僅包含各字形(glyph)的向量圖形而非各漢字部件的獨立曲線：

![《粉圓》「撩」字字形 Fontforge 編輯界面截圖](https://user-images.githubusercontent.com/13408130/198898646-defc207b-3898-4daa-adbb-d94b6cdce701.png "《粉圓》「撩」字字形 Fontforge 編輯界面截圖")

再沒有源碼文件的情況下有意對「粉圓」進行大規模改作的人就必須付出類似於「拆 5000 多字筆劃」的額外成本，難以繼承貴司前輩們的成就，實屬可惜

另一方面在[「粉圓」專案的議題追蹤系統](https://github.com/justfont/open-huninn-font/issues)中已經建檔許多已知問題(#30, #31, #32, #36, #37)以及完善建議(#5, #40)。鄙人了解貴司不可能恣意地將資源花費在解決非商業產品的問題上，為了字型的永續發展提供編輯用源碼讓社群可以自行滿足需求甚至是將貢獻回饋回這個專案是非常重要的

敬請斟酌考慮釋出字型源碼（原始編輯用設計文件），讓粉圓的「米」字旁變得更加引人著迷

[![](https://user-images.githubusercontent.com/13408130/198903548-9ba045a4-18e1-44f0-9cc6-0f3afaffca81.png "《來杯透心涼的粉圓吧，別客氣，我請客！. 或許，已經沒有多少人有印象了 … | by Michael Yeh | Medium》封面圖")](https://medium.com/@jf.michael/%E4%BE%86%E6%9D%AF%E9%80%8F%E5%BF%83%E6%B6%BC%E7%9A%84%E7%B2%89%E5%9C%93%E5%90%A7-%E5%88%A5%E5%AE%A2%E6%B0%A3-%E6%88%91%E8%AB%8B%E5%AE%A2-13ba1e0d59cc)

祝萬事順利  
林博仁  
<Buo.Ren.Lin@gmail.com>

---

## 參考資料

### 《粉圓》字型的相關資訊

* [open 粉圓 - justfont](https://justfont.com/huninn/)
* [免費的粉圓字體，要吃嗎？先看看粉圓的設計尬聊 , justfont blog](https://blog.justfont.com/2020/02/huninn-preview/)
* [來杯透心涼的粉圓吧，別客氣，我請客！. 或許，已經沒有多少人有印象了 … | by Michael Yeh | Medium](https://medium.com/@jf.michael/%E4%BE%86%E6%9D%AF%E9%80%8F%E5%BF%83%E6%B6%BC%E7%9A%84%E7%B2%89%E5%9C%93%E5%90%A7-%E5%88%A5%E5%AE%A2%E6%B0%A3-%E6%88%91%E8%AB%8B%E5%AE%A2-13ba1e0d59cc)
* [粉圓計畫：在上傳與下載之間，我們分享 , justfont blog](https://blog.justfont.com/2019/04/huninn-2020/)

### 《粉圓》字型既有衍生專案

主要使用程式進行批量調整而非對個別字形(glyph)進行修改

* [max32002/TaiwanPearl](https://github.com/max32002/TaiwanPearl)
* [max32002/FakePearl: A free font family derived from open-huninn-font.](https://github.com/max32002/FakePearl)
* [YuPearl/python at master · max32002/YuPearl](https://github.com/max32002/YuPearl/tree/master/python)

### 開源字型社群貢獻範例

* [V3.000 mastered by m4rc1e · Pull Request #2 · avrahamcornfeld/Varela-Round-Hebrew](https://github.com/avrahamcornfeld/Varela-Round-Hebrew/pull/2)  
  為上游字型新增了 499 個字形(glyph)

**Comment by rutopio** [comment]
您好，

我們在將小杉圓體改製成粉圓時，僅視情況將部分字拆了兩三個關鍵部位進行微調整與位移，並沒有把所有筆畫都拆開。

此外，原始小杉圓體的輪廓有失真、節點太少、非圓滑變形的現象，估計是 Motoya 公司用程式將黑體轉圓體所致，並不像 Adobe 與 Google 的思源系列一樣輪廓精良，可供後續的程式計算去變形或改作。

若您真的想要筆畫拆開版的話，並非找我們要第二手的拆開筆畫資料，而是建議您去和小杉圓體的創作者 Motoya 公司，表達想要 raw data 的筆畫拆開版本，那才會是相較之下比較正確的原始檔案。
