### ISSUE TITLE
更新希腊文，西里尔文字符（及部分西文字符更新）

### ISSUE THREAD

**Issue by NightFurySL2001** [justfont/open-huninn-font#40]
原版小杉圆体所制作的希腊文和西里尔文（Greek & Cyrillic）为全宽字符，这里提供衍生版糖圆体所重新制作的字符版本。下列为已更新字符：

ΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩαβγδεζηθικλμνξοπρστυφϕχψωςАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯЅІЈабвгдеёжзийклмнопрстуфхцчшщъыьэюяѕіј

另外全宽字符为统一风格也重做了一遍，部分数字字符也进行了更动。

ＡＢＣＤＥＦＧＨＩＪＫＬＭＮＯＰＱＲＳＴＵＶＷＸＹＺａｂｃｄｅｆｇｈｉｊｋｌｍｎｏｐｑｒｓｔｕｖｗｘｙｚ０１２３４５６７８９①②③④⑤⑥⑦⑧⑨⑩ⅠⅡⅢⅣⅤⅥⅦⅧⅨⅩⅪⅫ

[huninn-latin-fix.zip](https://github.com/justfont/open-huninn-font/files/8875026/huninn-latin-fix.zip)

**Comment by rutopio** [comment]
謝謝您告訴我們，這個會在未來的新版本中併入糖圆体的希臘字符及西里爾字符。

在此也特別感謝糖圆体的設計師。
