### ISSUE TITLE
更新廣東話字符

### ISSUE THREAD

**Issue by hellokoman** [justfont/open-huninn-font#41]
請問有可能可以支援廣東話的字符嗎?
例如以下常用廣東話字符

嘅  咗  啲  喺  哋  嘢  撳  嚟

如果有幸能夠支援的話 可以更好支援香港開發的App / 網頁 🙏🏻

**Comment by rutopio** [comment]
您好，粉圓體是以收錄臺灣常用漢字及臺客語用字為主，目前並無增補粵語字的計畫呦。

至於您所說的「支援香港開發的 App / 網頁」一事，我們會納入未來其他計畫的考慮，謝謝。

**Comment by hellokoman** [comment]
非常感謝『粉圓』持續更新
特別是對廣東話的字符支援！
