### ISSUE TITLE
惪 (U+60EA) 的「直」部不一致

### ISSUE THREAD

**Issue by Marcus98T** [justfont/open-huninn-font#43]
由於原規格分離原則，建議 copy 悳 (U+60B3) 到 惪 (U+60EA)

<img width="328" alt="Screenshot 2023-03-15 at 02 59 44" src="https://user-images.githubusercontent.com/10541683/225109720-f84408a1-49ae-45fb-8372-0b1cd33cbf56.png">

**Comment by UltimateAmitieKaiNiC** [comment]
可以在下一年的更新

**Comment by rutopio** [comment]
`悳` (U+60B3) 與 `惪` (U+60EA) 因原規格分離原則而分開編碼，類似 `値` (U+5024) 與 `值` (U+503C) 的關係，因此這裡選擇保留直的兩種字源造型以作為兩字的區別。

Reference:
- [Possible unification (eisoch/irg)](https://github.com/eisoch/irg/issues/28)
