### ISSUE TITLE
禄（U+7984）字還有ネ部

### ISSUE THREAD

**Issue by Marcus98T** [justfont/open-huninn-font#44]
如果「礼」（U+793C）和「禅」（U+7985）有示部，為何「禄」（U+7984）字還有ネ部？

<img width="750" alt="Screenshot 2023-03-16 at 21 20 05" src="https://user-images.githubusercontent.com/10541683/225632352-241de33e-d064-4dbe-8233-f836a4a589a2.png">

**Comment by UltimateAmitieKaiNiC** [comment]
還有辺

**Comment by rutopio** [comment]
謝謝提醒，「禄」與「辺」皆已於 `2.1` 版本中修正。
