### ISSUE TITLE
禇（U+7987）的者部不一致

### ISSUE THREAD

**Issue by Marcus98T** [justfont/open-huninn-font#45]
「禇」字是粉圓v2增加的，不是 Kosugi Maru 原字。除非「者」部要加點（舊字形），這字不應該有點。

<img width="388" alt="Screenshot 2023-03-16 at 21 33 01" src="https://user-images.githubusercontent.com/10541683/225633263-783f9401-4361-4e85-85f8-845ed5a31c35.png">

**Comment by rutopio** [comment]
謝謝提醒，「者」偏旁的字符皆於 `2.1` 版本中統一。

<img width="942" alt="image" src="https://github.com/user-attachments/assets/a68f0d30-d937-422f-92b0-b9241f27b7b4">
