### ISSUE TITLE
「戶」（U+6236）和「魲」（U+9B72）不是戸部

### ISSUE THREAD

**Issue by CoolMarvel43** [justfont/open-huninn-font#46]
我知道「戶」（U+6236）字跟「戸」（U+6238）字設計有區別，但是如果字形要統一一點，可以考慮 copy「戸」到「戶」？

另外，「魲」字在 v2 還是「戶」部，可以考慮 fix 嗎？

<img width="776" alt="Screenshot 2023-03-16 at 21 45 33" src="https://user-images.githubusercontent.com/10541683/225636475-b39e9d04-c26a-4841-be85-8c9cf8d6ddaa.png">

**Comment by rutopio** [comment]
謝謝提醒，「戶」偏旁的字符皆於 `2.1` 版本中統一。

<img width="1059" alt="image" src="https://github.com/user-attachments/assets/fccefb90-a792-4079-b2a2-3bfea7370404">
