### ISSUE TITLE
v2.0 vs. v1.1 版本差異的字型問題

### ISSUE THREAD

**Issue by ChiaYuSu** [justfont/open-huninn-font#48]
Hi，感謝您推出這麼棒的字體供大家使用，這裡有幾個問題想問看看是否有機會能夠推出下一版並修復

### 行距沒有垂直置中
- v1.1 沒有這個問題
  - 按鈕
  ![image](https://user-images.githubusercontent.com/26423040/228724503-5b2c29be-c326-4335-b22f-56a6c789508f.png)
  - 標籤
  ![image](https://user-images.githubusercontent.com/26423040/228724674-cba5be0d-c80e-4a6a-b41c-733aa2774c6d.png)
- v2.0
  - 按鈕（文字部分比較偏下）
  ![image](https://user-images.githubusercontent.com/26423040/228725031-30bb064b-8cfd-4e4a-8858-8135871bf6f4.png)
  - 標籤（0 的位置比較偏下）
  ![image](https://user-images.githubusercontent.com/26423040/228725099-007deea4-9045-4602-b571-85ff719f25f5.png)

### 同樣解析度下（100%）某些字的某些筆畫看起來很粗
- v1.1 沒有這個問題
  ![image](https://user-images.githubusercontent.com/26423040/228725464-0d953620-138b-4676-94e2-79097a34caa9.png)
- v2.0（站、使、用、供、之等多個字）
  ![image](https://user-images.githubusercontent.com/26423040/228725558-4cf4a529-7efc-4394-aaf4-c8dee224a611.png)

**Comment by NightFurySL2001** [comment]
在本人搬迁糖圆体至 2.0 时发现此问题并排查，发现粉圆 2.0 的纵向参数相对 1.0/1.1 有重大修改。1.0/1.1版的纵向参数 ascender/descender 是 871/-153，但在 2.0版的值是 880/-120。此字体使用的 UPM 值是 1024，相信是 justfont 在人员更动后新的维护者并未注意 UPM 和平常OTF字体的 1000 不同，因此特意修改纵向参数符合OTF的习惯导致 2.0 版本异常。

**Comment by rutopio** [comment]
`2.0` 的度量設置有誤，於 `2.1` 版本中已經恢復度量為 `1.0` 版本的設定，應可兼容您所提的問題。

- Ascender: `871`
- Descender: `-153`
- UPM: `1024`

> Hi，感謝您推出這麼棒的字體供大家使用，這裡有幾個問題想問看看是否有機會能夠推出下一版並修復
> 
> ### 行距沒有垂直置中
> * v1.1 沒有這個問題
>   
>   * 按鈕
>     ![image](https://user-images.githubusercontent.com/26423040/228724503-5b2c29be-c326-4335-b22f-56a6c789508f.png)
>   * 標籤
>     ![image](https://user-images.githubusercontent.com/26423040/228724674-cba5be0d-c80e-4a6a-b41c-733aa2774c6d.png)
> * v2.0
>   
>   * 按鈕（文字部分比較偏下）
>     ![image](https://user-images.githubusercontent.com/26423040/228725031-30bb064b-8cfd-4e4a-8858-8135871bf6f4.png)
>   * 標籤（0 的位置比較偏下）
>     ![image](https://user-images.githubusercontent.com/26423040/228725099-007deea4-9045-4602-b571-85ff719f25f5.png)
> 
> ### 同樣解析度下（100%）某些字的某些筆畫看起來很粗
> * v1.1 沒有這個問題
>   ![image](https://user-images.githubusercontent.com/26423040/228725464-0d953620-138b-4676-94e2-79097a34caa9.png)
> * v2.0（站、使、用、供、之等多個字）
>   ![image](https://user-images.githubusercontent.com/26423040/228725558-4cf4a529-7efc-4394-aaf4-c8dee224a611.png)
