### ISSUE TITLE
遂的部件有的不一致

### ISSUE THREAD

**Issue by UltimateAmitieKaiNiC** [justfont/open-huninn-font#49]
希望未來版本趕緊修改
![image](https://user-images.githubusercontent.com/67255901/230600385-91d72cc4-6bc3-4794-95a7-ab5e2ed20d7b.png)

**Comment by rutopio** [comment]
謝謝提醒，`㒸` 偏旁的字符已於 `2.1` 版本中統一部件。

<img width="990" alt="image" src="https://github.com/user-attachments/assets/35d9b1fc-a2a3-42d9-862f-edeff3e9dcd4">
