### ISSUE TITLE
希望可以增加不同粗細度的版本

### ISSUE THREAD

**Issue by gamania31610** [justfont/open-huninn-font#5]
希望可以增加不同粗細度的版本，如同思源黑體般有Light,Normal,Medium,Heavy等不同粗細

**Comment by RuixiZhang42** [comment]
@gamania31610 「小杉圓體」只有一個字重……要把「粉圓」變成多字重的「字型家族」，細體和粗體得從零開始繪製吧……感覺短期內是不太可能做出來的

**Comment by max32002** [comment]
試看看這一個版本：
https://github.com/max32002/open-huninn-font

**Comment by KrasnayaPloshchad** [comment]
個人認為可以先把粉圓加工成可變字型，使文字粗細度能隨用戶調整而變化，再根據變量生成不同粗細的版本。微軟在公佈 OpenType 1.8 的時候就在裏面提出過這個方案。
https://docs.microsoft.com/en-us/typography/opentype/spec/otvaroverview#dynamic-generation-of-static-instance-fonts
