### ISSUE TITLE
希望能新增「牳」字

### ISSUE THREAD

**Issue by 7f0019** [justfont/open-huninn-font#50]
感謝製作團隊做了很棒的字型給大家！

因為工作需求經常使用到「牳」字，但可惜的是牳缺字，後續如果有更新的話希望能補上，謝謝製作團隊 m(_ _)m

**Comment by rutopio** [comment]
`牳` 字已於 `2.1` 版本中新增。

<img width="721" alt="image" src="https://github.com/user-attachments/assets/67cf4970-9152-4350-8386-548ef7ca1be1">
