### ISSUE TITLE
建議修改「壓」的字形

### ISSUE THREAD

**Issue by chlbc** [justfont/open-huninn-font#6]
如題，建議將「壓」的字形修改成「厂」的左邊那撇撇到最下面的版本

![01](https://user-images.githubusercontent.com/42777336/76682014-4da14000-6633-11ea-9466-0a2f26995adc.png)

**Comment by NightFurySL2001** [comment]
”壓“ 系列需要统一。
![image](https://user-images.githubusercontent.com/33471049/82005935-492bee80-9699-11ea-9bca-f2d15c7ecfef.png)

**Comment by rutopio** [comment]
此為原本小杉圓體的特色，在粉圓體中我們決定保持原樣。

不過，本專案以 OFL 開源授權釋出，若您對該部分的筆形有調整的需求，您可以自由下載、改作、發布，無需特別知會。
