### ISSUE TITLE
專案資料夾內缺少小杉圓體與 Varela Round 著作資訊與授權聲明

### ISSUE THREAD

**Issue by zerng07** [justfont/open-huninn-font#7]
下載的字型檔中有授權聲明，不過專案資料夾內沒有，若附上能讓使用者或開發者更清楚。

建議可以開一個檔案寫著作權人與授權方式。

內容同字型檔：
[Kosugi Maru]
Copyright(C)2010 MOTOYA CO.,LTD.      

[Varela Round]
Copyright 2011-2016 The Varela Round Project Authors (https://github.com/alefalefalef/Varela-Round-Hebrew/), with Reserved Font Names 'Varela' and 'Varela Round'.      

[jf open huninn]
2020(c )The jf open huninn font is redistributed by justfont CO.,LTD. under SIL Open Font License. The Hanzi part of this project was derived from Kosugi Maru under Apache-2.0 (https://www.apache.org/licenses/LICENSE-2.0).

可以放在 OFL license txt 檔的開頭；或是另外開個 COPYRIGHT 檔案；或是以 AUTHORS + CONTRIBUTORS 檔案的方式放放亦可。

註：最後一種做法可以參考 
https://github.com/avrahamcornfeld/Varela-Round-Hebrew/blob/master/AUTHORS.txt
https://github.com/avrahamcornfeld/Varela-Round-Hebrew/blob/master/CONTRIBUTORS.txt

**Comment by medicalwei** [comment]
授權聲明應該要包含 With Reserved Font Names "Verala" and "Verala Round"

**Comment by miggo** [comment]
已經將授權聲明加入到 license.txt 中，多謝您的建議！
