### ISSUE TITLE
引號、括號、書名號的位置

### ISSUE THREAD

**Issue by lapomme** [justfont/open-huninn-font#8]
可以把（）、【】、「」、『』等標點符號改成置中的樣式嗎？

https://github.com/adobe-fonts/source-han-serif/issues/73

> ![image](https://user-images.githubusercontent.com/27000939/76685357-5d943200-65e9-11ea-9717-1ec98d8d0f9f.png)

**Comment by rutopio** [comment]
謝謝您告訴我們，我們會在未來的新版本中修正。

It will be fixed in our upcoming version soon, thank you.
