### ISSUE TITLE
「卝」、「艹」部件

### ISSUE THREAD

**Issue by lapomme** [justfont/open-huninn-font#9]
這個字型分辨「卝」和「艹」部件嗎？「敬」字寫作「卝」，但「夢」、「觀」、「寬」、「護」等字寫作「艹」。

**Comment by rutopio** [comment]
謝謝您告訴我們，我們會在未來的新版本中修正，將統一成連字的「艹」。。

It will be fixed in our upcoming version soon, thank you.
